---
rules:
  NO_ENTITIES_WITHOUT_EVENTS: false
  NO_EMPTY_EVENT_APPLY: true
  NO_EMPTY_ENUMS: true
  NO_TYPES_WITHOUT_FIELDS: true
  NO_ENTITY_WITHOUT_PARENT: true
  NO_ENTITY_WITHOUT_ACTIVE_WHEN: true
  NO_CHILD_ENTITY_WITHOUT_ROOT_ID: true
  NO_ENTITY_WITHOUT_ID: true
  NO_EVENT_WITHOUT_ID: true
  NO_EVENT_WITHOUT_ROOT_ID: true
  NO_MULTIPLE_IDS_FOR_ROOT_ENTITY: true
  NO_RAW_TYPE_MAPS: true
  NO_RAW_TYPE_LISTS: true
  NO_OBJECTS_WITHOUT_FIELDS: true
  NO_ENTITY_EVENTS_FOR_SHARED_EVENT: true
  NO_EVENT_WITHOUT_ENTITY: true
  NO_ID_AS_SECONDARY_KEY: true
  NO_QUERIES_WITHOUT_RESPONSE: true
  NO_COMMANDS_WITHOUT_RESPONSE: true

features:
  BIG_DECIMAL_EXPRESSION_PARSING: true
  ENUM_EXPRESSION_MINIFY: true
